apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: mysql
          env:
          - name: MYSQL_INITDB_DATABASE
            value: indigo
          - name: MYSQL_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                key: mysql-username
          - name: mysql_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                key: mysql-password
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-volume
              mountPath: /data/db
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-pvc