apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  mysql-username: {{ .Values.secret.mysql_username }}
  mysql-password: {{ .Values.secret.mysql_password }}